### Setting up input

In [1]:
import pandas as pd
df = pd.read_csv('../../../tests/resources/100_comments.csv')
df

                                             Comments  CommentId
0   My salad had a bland vinegrette on the baby gr...        561
1                            Appetite instantly gone.        997
2                   The only downside is the service.        321
3           We waited for forty five minutes in vain.        153
4   It took over 30 min to get their milkshake, wh...         74
..                                                ...        ...
95  You get incredibly fresh fish, prepared with c...        296
96                            I give it 2 thumbs down        149
97                              AN HOUR... seriously?        569
98  On the up side, their cafe serves really good ...        100
99  Del Taco is pretty nasty and should be avoided...        965

[100 rows x 2 columns]

### Running `extra-model`

In [5]:
from extra_model._run import run_from_dataframe
from pathlib import Path

res = run_from_dataframe(df, embeddings_path='../../../embeddings')
res

/usr/lib/python3.9/site-packages/extra_model-0.3.0-py3.9.egg/extra_model/_disambiguate.py:111: RuntimeWarning: invalid value encountered in true_divide
  contexts = [np.divide(context, np.linalg.norm(context)) for context in contexts]

,Position,Aspect,Descriptor,AspectCount,WordnetNode,SentimentCompound,SentimentBinary,AdCluster,CommentId,Topic,TopicImportance,TopicSentimentCompound,TopicSentimentBinary,TopicCount
0,9,downside,only,1,downside.n.01,0.0000,0.0,only,321,downside.n.01,0.007051,0.000000,0.000000,1
1,65,chips,many,1,chip.n.04,0.0000,0.0,many,303,food.n.01,0.032798,-0.073582,-0.090909,11
2,77,treat,real,1,dainty.n.01,0.0000,0.0,real,356,food.n.01,0.032798,-0.073582,-0.090909,11
3,33,food,mediocre,4,food.n.01,0.0000,0.0,mediocre,932,food.n.01,0.032798,-0.073582,-0.090909,11
4,6,food,Worst,4,food.n.01,-0.6249,-1.0,Worst,860,food.n.01,0.032798,-0.073582,-0.090909,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,51,trap,old,1,trap.n.02,0.0000,0.0,old,82,trap.n.02,0.014101,0.000000,0.000000,2
73,51,grease trap,old,1,trap.n.02,0.0000,0.0,old,82,trap.n.02,0.014101,0.000000,0.000000,2
74,24,piece,long,1,piece.n.06,0.0000,0.0,long,881,piece.n.06,0.007051,0.000000,0.000000,1
75,71,bit,little,1,bit.n.05,0.0000,0.0,little,984,bit.n.05,0.007051,0.000000,0.000000,1
76,25,fish,fresh,1,fish.n.02,0.3182,1.0,fresh,296,fish.n.02,0.007051,0.318200,1.000000,1